# Generated by Django 6.0.2 on 2026-02-19 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(editable=False, max_length=9, verbose_name='Année scolaire')),
                ('debut', models.IntegerField(verbose_name='Début')),
                ('fin', models.IntegerField(verbose_name='Fin')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='TableClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('lib_classe', models.CharField(max_length=50, verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='TableEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom1', models.CharField(max_length=20, verbose_name='Premier prénom')),
                ('prenom2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Second prénom')),
                ('prenom3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Troisième prénom')),
                ('fullname', models.CharField(blank=True, null=True, verbose_name='Nom complet')),
                ('sexe', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin'), ('O', 'Autre')], default='O', max_length=1, verbose_name='Sexe')),
                ('jour_naissance', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=0, verbose_name='Jour')),
                ('mois_naissance', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=0, verbose_name='Mois')),
                ('annee_naissance', models.IntegerField(choices=[(0, '0000'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], default=0, help_text="Sélectionnez 0000 si l'année est inconnue", verbose_name='Année')),
                ('date_naissance', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de Naissance')),
                ('pere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Père')),
                ('mere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mère')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photoeleves/%Y/%m/%d/', verbose_name='Photo')),
                ('dateajout', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Elève',
                'verbose_name_plural': 'Elèves',
                'ordering': ['prenom1'],
            },
        ),
        migrations.CreateModel(
            name='TableNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=50, unique=True, verbose_name='Niveau')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='TableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50, unique=True, verbose_name='Option')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='TablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50, unique=True, verbose_name='permission')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='TableRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True, verbose_name='Rôle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
        migrations.CreateModel(
            name='TableAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_aff', models.CharField(blank=True, choices=[('Nouv', 'Nouveau/elle'), ('adm', 'Admis/e'), ('red', 'Redoublant/e'), ('Cdt', 'Candidat/e libre'), ('Aut', 'Autre')], default='Aut', max_length=5, null=True, verbose_name='Etat affectation')),
                ('date_aff', models.DateTimeField(auto_now_add=True, verbose_name='Date affectation')),
                ('annee_aff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tableannee', verbose_name='Année scolaire')),
                ('classe_aff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tableclasse', verbose_name='Classe')),
                ('eleve_aff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tableeleve', verbose_name='Elève')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-annee_aff', 'eleve_aff__prenom1'],
            },
        ),
        migrations.CreateModel(
            name='TableFraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_annuel', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Frais de scolaire')),
                ('t1_fs', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='1ère Tranche')),
                ('t2_fs', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='2ème Tranche')),
                ('t3_fs', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='3ème Tranche')),
                ('annee_fs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tableannee', verbose_name='Année scolaire')),
                ('classe_fs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tableclasse', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Frais de scolarité',
                'verbose_name_plural': 'Frais de scolarité',
            },
        ),
        migrations.AddField(
            model_name='tableclasse',
            name='niveau_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tableniveau', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='tableclasse',
            name='option_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tableoption', verbose_name='Option'),
        ),
        migrations.CreateModel(
            name='TableRecouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_ar', models.CharField(blank=True, choices=[('Ins', 'Inscription'), ('Reins', 'Réinscription'), ('Aut', 'Autre')], default='Aut', max_length=5, null=True, verbose_name='Statut')),
                ('montant_statut_ar', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reduction', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reduction(%)')),
                ('frais_paiement', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais')),
                ('tranche1_paiement', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='1ère Tranche')),
                ('tranche2_paiement', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2ème Tranche')),
                ('tranche3_paiement', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3ème Tranche')),
                ('tuteur_paiement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tuteur/trice')),
                ('contact_tuteur_paiement', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact')),
                ('adresse_tuteur_paiement', models.CharField(blank=True, max_length=300, null=True, verbose_name='Adresse')),
                ('profession_tuteur_paiement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('total_paye', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total payé')),
                ('v1', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 1')),
                ('d1', models.DateField(blank=True, null=True, verbose_name='Date v.1')),
                ('v2', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 2')),
                ('d2', models.DateField(blank=True, null=True, verbose_name='Date v.2')),
                ('v3', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 3')),
                ('d3', models.DateField(blank=True, null=True, verbose_name='Date v.3')),
                ('v4', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 4')),
                ('d4', models.DateField(blank=True, null=True, verbose_name='Date v.4')),
                ('v5', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 5')),
                ('d5', models.DateField(blank=True, null=True, verbose_name='Date v.5')),
                ('v6', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 6')),
                ('d6', models.DateField(blank=True, null=True, verbose_name='Date v.6')),
                ('v7', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 7')),
                ('d7', models.DateField(blank=True, null=True, verbose_name='Date v.7')),
                ('v8', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 8')),
                ('d8', models.DateField(blank=True, null=True, verbose_name='Date v.8')),
                ('v9', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 9')),
                ('d9', models.DateField(blank=True, null=True, verbose_name='Date v.9')),
                ('v10', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 10')),
                ('d10', models.DateField(blank=True, null=True, verbose_name='Date v.10')),
                ('v11', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 11')),
                ('d11', models.DateField(blank=True, null=True, verbose_name='Date v.11')),
                ('v12', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Vers. 12')),
                ('d12', models.DateField(blank=True, null=True, verbose_name='Date v.12')),
                ('affectation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tableaffectation', verbose_name='Effectation')),
            ],
            options={
                'verbose_name': 'Recouvrement',
                'verbose_name_plural': 'Recouvrements',
            },
        ),
        migrations.CreateModel(
            name='TableUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(unique=True, verbose_name="Nom d'utilisateur")),
                ('nom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom(s)')),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('dateajout', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('derniereconnection', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photousers/', verbose_name='photo')),
                ('statut', models.CharField(choices=[('On', 'Actif'), ('Off', 'Inactif')], default='On', max_length=3)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tablepermission', verbose_name='Permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tablerole', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.AddConstraint(
            model_name='tableaffectation',
            constraint=models.UniqueConstraint(fields=('eleve_aff', 'classe_aff', 'annee_aff'), name='unique_affectation'),
        ),
    ]
