# Generated by Django 6.0.2 on 2026-02-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableutilisateur',
            name='statut',
            field=models.CharField(choices=[('On', 'Actif'), ('Off', 'Inactif')], default='On', max_length=3, verbose_name='Statut'),
        ),
    ]
