# Generated by Django 6.0.2 on 2026-02-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_tableutilisateur_statut'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tableaffectation',
            name='unique_affectation',
        ),
        migrations.AddConstraint(
            model_name='tableaffectation',
            constraint=models.UniqueConstraint(fields=('eleve_aff', 'classe_aff', 'annee_aff'), name='unique_affectation1'),
        ),
        migrations.AddConstraint(
            model_name='tableaffectation',
            constraint=models.UniqueConstraint(fields=('eleve_aff', 'annee_aff'), name='unique_affectation2'),
        ),
    ]
