# Generated by Django 6.0.2 on 2026-02-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_tableaffectation_unique_affectation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableclasse',
            name='niveau_classe',
            field=models.CharField(blank=True, choices=[('cre', 'Crèche'), ('mat', 'Maternel'), ('pri', 'Primaire'), ('clg', 'Collège'), ('lyc', 'Lycée'), ('aut', 'Autres')], default='aut', max_length=3, null=True, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='tableclasse',
            name='option_classe',
            field=models.CharField(blank=True, choices=[('se', 'Sciences Expérimentales'), ('sm', 'Sciences Mathématiques'), ('ss', 'Sciences Sociales'), ('sc', 'Scientifiques'), ('lit', 'Littéraires'), ('aut', 'Autres')], default='aut', max_length=3, null=True, verbose_name='Option'),
        ),
    ]
