# Generated by Django 6.0.2 on 2026-02-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_tableclasse_niveau_classe_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tablerecouvrement',
            constraint=models.UniqueConstraint(fields=('affectation',), name='unique_rec'),
        ),
    ]
